// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election.proto

package pipe.election;

public final class Election {
  private Election() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LeaderStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    pipe.election.Election.LeaderStatus.LeaderQuery getAction();

    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    pipe.election.Election.LeaderStatus.LeaderState getState();

    /**
     * <code>optional string leader_host = 3;</code>
     */
    boolean hasLeaderHost();
    /**
     * <code>optional string leader_host = 3;</code>
     */
    java.lang.String getLeaderHost();
    /**
     * <code>optional string leader_host = 3;</code>
     */
    com.google.protobuf.ByteString
        getLeaderHostBytes();

    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    int getLeaderId();
  }
  /**
   * Protobuf type {@code LeaderStatus}
   *
   * <pre>
   * enquire about the state of the leader/election
   * </pre>
   */
  public static final class LeaderStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LeaderStatus)
      LeaderStatusOrBuilder {
    // Use LeaderStatus.newBuilder() to construct.
    private LeaderStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LeaderStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LeaderStatus defaultInstance;
    public static LeaderStatus getDefaultInstance() {
      return defaultInstance;
    }

    public LeaderStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              pipe.election.Election.LeaderStatus.LeaderQuery value = pipe.election.Election.LeaderStatus.LeaderQuery.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              pipe.election.Election.LeaderStatus.LeaderState value = pipe.election.Election.LeaderStatus.LeaderState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              leaderHost_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              leaderId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.election.Election.internal_static_LeaderStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.election.Election.internal_static_LeaderStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.election.Election.LeaderStatus.class, pipe.election.Election.LeaderStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<LeaderStatus> PARSER =
        new com.google.protobuf.AbstractParser<LeaderStatus>() {
      public LeaderStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaderStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LeaderStatus> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code LeaderStatus.LeaderState}
     */
    public enum LeaderState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEADERUNKNOWN = 1;</code>
       */
      LEADERUNKNOWN(0, 1),
      /**
       * <code>LEADERALIVE = 2;</code>
       */
      LEADERALIVE(1, 2),
      /**
       * <code>LEADERDEAD = 3;</code>
       */
      LEADERDEAD(2, 3),
      ;

      /**
       * <code>LEADERUNKNOWN = 1;</code>
       */
      public static final int LEADERUNKNOWN_VALUE = 1;
      /**
       * <code>LEADERALIVE = 2;</code>
       */
      public static final int LEADERALIVE_VALUE = 2;
      /**
       * <code>LEADERDEAD = 3;</code>
       */
      public static final int LEADERDEAD_VALUE = 3;


      public final int getNumber() { return value; }

      public static LeaderState valueOf(int value) {
        switch (value) {
          case 1: return LEADERUNKNOWN;
          case 2: return LEADERALIVE;
          case 3: return LEADERDEAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LeaderState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LeaderState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LeaderState>() {
              public LeaderState findValueByNumber(int number) {
                return LeaderState.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pipe.election.Election.LeaderStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final LeaderState[] VALUES = values();

      public static LeaderState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LeaderState(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LeaderStatus.LeaderState)
    }

    /**
     * Protobuf enum {@code LeaderStatus.LeaderQuery}
     */
    public enum LeaderQuery
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WHOISTHELEADER = 1;</code>
       */
      WHOISTHELEADER(0, 1),
      /**
       * <code>THELEADERIS = 2;</code>
       */
      THELEADERIS(1, 2),
      ;

      /**
       * <code>WHOISTHELEADER = 1;</code>
       */
      public static final int WHOISTHELEADER_VALUE = 1;
      /**
       * <code>THELEADERIS = 2;</code>
       */
      public static final int THELEADERIS_VALUE = 2;


      public final int getNumber() { return value; }

      public static LeaderQuery valueOf(int value) {
        switch (value) {
          case 1: return WHOISTHELEADER;
          case 2: return THELEADERIS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LeaderQuery>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LeaderQuery>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LeaderQuery>() {
              public LeaderQuery findValueByNumber(int number) {
                return LeaderQuery.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pipe.election.Election.LeaderStatus.getDescriptor().getEnumTypes().get(1);
      }

      private static final LeaderQuery[] VALUES = values();

      public static LeaderQuery valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LeaderQuery(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LeaderStatus.LeaderQuery)
    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private pipe.election.Election.LeaderStatus.LeaderQuery action_;
    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
     */
    public pipe.election.Election.LeaderStatus.LeaderQuery getAction() {
      return action_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private pipe.election.Election.LeaderStatus.LeaderState state_;
    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .LeaderStatus.LeaderState state = 2;</code>
     */
    public pipe.election.Election.LeaderStatus.LeaderState getState() {
      return state_;
    }

    public static final int LEADER_HOST_FIELD_NUMBER = 3;
    private java.lang.Object leaderHost_;
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public boolean hasLeaderHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public java.lang.String getLeaderHost() {
      java.lang.Object ref = leaderHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderHostBytes() {
      java.lang.Object ref = leaderHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADER_ID_FIELD_NUMBER = 4;
    private int leaderId_;
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    private void initFields() {
      action_ = pipe.election.Election.LeaderStatus.LeaderQuery.WHOISTHELEADER;
      state_ = pipe.election.Election.LeaderStatus.LeaderState.LEADERUNKNOWN;
      leaderHost_ = "";
      leaderId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLeaderHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, leaderId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLeaderHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, leaderId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pipe.election.Election.LeaderStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pipe.election.Election.LeaderStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LeaderStatus}
     *
     * <pre>
     * enquire about the state of the leader/election
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderStatus)
        pipe.election.Election.LeaderStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.election.Election.internal_static_LeaderStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.election.Election.internal_static_LeaderStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.election.Election.LeaderStatus.class, pipe.election.Election.LeaderStatus.Builder.class);
      }

      // Construct using pipe.election.Election.LeaderStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = pipe.election.Election.LeaderStatus.LeaderQuery.WHOISTHELEADER;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = pipe.election.Election.LeaderStatus.LeaderState.LEADERUNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.election.Election.internal_static_LeaderStatus_descriptor;
      }

      public pipe.election.Election.LeaderStatus getDefaultInstanceForType() {
        return pipe.election.Election.LeaderStatus.getDefaultInstance();
      }

      public pipe.election.Election.LeaderStatus build() {
        pipe.election.Election.LeaderStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.election.Election.LeaderStatus buildPartial() {
        pipe.election.Election.LeaderStatus result = new pipe.election.Election.LeaderStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.leaderHost_ = leaderHost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.leaderId_ = leaderId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.election.Election.LeaderStatus) {
          return mergeFrom((pipe.election.Election.LeaderStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.election.Election.LeaderStatus other) {
        if (other == pipe.election.Election.LeaderStatus.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasLeaderHost()) {
          bitField0_ |= 0x00000004;
          leaderHost_ = other.leaderHost_;
          onChanged();
        }
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.election.Election.LeaderStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.election.Election.LeaderStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private pipe.election.Election.LeaderStatus.LeaderQuery action_ = pipe.election.Election.LeaderStatus.LeaderQuery.WHOISTHELEADER;
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public pipe.election.Election.LeaderStatus.LeaderQuery getAction() {
        return action_;
      }
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public Builder setAction(pipe.election.Election.LeaderStatus.LeaderQuery value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .LeaderStatus.LeaderQuery action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = pipe.election.Election.LeaderStatus.LeaderQuery.WHOISTHELEADER;
        onChanged();
        return this;
      }

      private pipe.election.Election.LeaderStatus.LeaderState state_ = pipe.election.Election.LeaderStatus.LeaderState.LEADERUNKNOWN;
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public pipe.election.Election.LeaderStatus.LeaderState getState() {
        return state_;
      }
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public Builder setState(pipe.election.Election.LeaderStatus.LeaderState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .LeaderStatus.LeaderState state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = pipe.election.Election.LeaderStatus.LeaderState.LEADERUNKNOWN;
        onChanged();
        return this;
      }

      private java.lang.Object leaderHost_ = "";
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public boolean hasLeaderHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public java.lang.String getLeaderHost() {
        java.lang.Object ref = leaderHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            leaderHost_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLeaderHostBytes() {
        java.lang.Object ref = leaderHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder setLeaderHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        leaderHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder clearLeaderHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderHost_ = getDefaultInstance().getLeaderHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder setLeaderHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        leaderHost_ = value;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000008;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LeaderStatus)
    }

    static {
      defaultInstance = new LeaderStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LeaderStatus)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LeaderStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016election.proto\"\202\002\n\014LeaderStatus\022)\n\006act" +
      "ion\030\001 \002(\0162\031.LeaderStatus.LeaderQuery\022(\n\005" +
      "state\030\002 \001(\0162\031.LeaderStatus.LeaderState\022\023" +
      "\n\013leader_host\030\003 \001(\t\022\021\n\tleader_id\030\004 \001(\005\"A" +
      "\n\013LeaderState\022\021\n\rLEADERUNKNOWN\020\001\022\017\n\013LEAD" +
      "ERALIVE\020\002\022\016\n\nLEADERDEAD\020\003\"2\n\013LeaderQuery" +
      "\022\022\n\016WHOISTHELEADER\020\001\022\017\n\013THELEADERIS\020\002B\021\n" +
      "\rpipe.electionH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LeaderStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LeaderStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LeaderStatus_descriptor,
        new java.lang.String[] { "Action", "State", "LeaderHost", "LeaderId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
